export { default as NewTraining } from './NewTraining'
export { default as Running } from './Running'
export { default as EndCycle } from './EndCycle'
export { default as EndTraining } from './EndTraining'
export { default as History } from './History'
export { default as Countdown } from './Countdown'
export { default as Recovery } from './Recovery'